title: Cohousing talks
description: "platforma pro komunitní, participativní, cohousingové bydlení"
baseurl: "/cohousingtalks"
url: "https://kubantjan.github.io"

markdown: kramdown
permalink: pretty

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
